spring:
  profiles:
    active: 
    - dev
---
spring:
  profiles:
    application: dev
        name: mircroservicecloud-config-yzj-dev
---
spring:
  profiles: test
    application:
        name: mircroservicecloud-config-yzj-test
    